Create a function named calculate() in mean_var_std.py that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

The returned dictionary should follow this format:

In [ ]:
from logging import exception

#{
  #'mean': [axis1, axis2, flattened],
  #'variance': [axis1, axis2, flattened],
  #'standard deviation': [axis1, axis2, flattened],
  #'max': [axis1, axis2, flattened],
 #'min': [axis1, axis2, flattened],
  #'sum': [axis1, axis2, flattened]
#}

If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.

For example, calculate([0,1,2,3,4,5,6,7,8]) should return:

In [ ]:
{
  'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
  'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667],
  'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611],
  'max': [[6, 7, 8], [2, 5, 8], 8],
  'min': [[0, 1, 2], [0, 3, 6], 0],
  'sum': [[9, 12, 15], [3, 12, 21], 36]
}

**Development**
Write your code in mean_var_std.py. For development, you can use main.py to test your code. In order to run your code, type python3 main.py into the GitPod terminal and hit enter. This will cause the included CPython interpreter to run the main.py file.

**Testing**
The unit tests for this project are in test_module.py. We imported the tests from test_module.py to main.py for your convenience.

-------------------------------START-------------------------------------------------------------------------

The input of the function should be a list containing 9 digits.

In [1]:
import numpy as np

In [49]:
matrix_list = [1, 2, 3, 4, 5, 6, 7, 8, 9]

The function should convert the list into a 3 x 3 Numpy array

In [50]:
mtrx = np.array(matrix_list).reshape(3,3)
print(mtrx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [46]:
mtrx

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.

Mean

In [37]:
list(mtrx.mean(axis=0)) #rows

[np.float64(4.0), np.float64(5.0), np.float64(6.0)]

In [38]:
list(mtrx.mean(axis=1)) #columns

[np.float64(2.0), np.float64(5.0), np.float64(8.0)]

In [40]:
mtrx.mean() #flattened

np.float64(5.0)

In [41]:
mean_dict = {
    'mean': [list(mtrx.mean(axis=0)), list(mtrx.mean(axis=1)), mtrx.mean()]
}

Variance

In [30]:
var_dict = {
    'variance': [list(mtrx.var(axis=0)), list(mtrx.var(axis=1)), mtrx.var()]
}

Standard Deviation

In [31]:
dev_dict = {
    'standard deviation': [list(mtrx.std(axis=0)), list(mtrx.std(axis=1)), mtrx.std()]
}

Max

In [32]:
max_dict = {
    'max': [list(mtrx.max(axis=0)), list(mtrx.max(axis=1)), mtrx.max()]
}

Min

In [33]:
min_dict = {
    'min': [list(mtrx.min(axis=0)), list(mtrx.min(axis=1)), mtrx.min()]
}

Sum

In [34]:
sum_dict = {
    'sum': [list(mtrx.sum(axis=0)), list(mtrx.sum(axis=1)), mtrx.sum()]
}

Merging it in the one dictionary

In [42]:
calc_dict = {
    'mean': [list(mtrx.mean(axis=0)), list(mtrx.mean(axis=1)), mtrx.mean()],
    'variance': [list(mtrx.var(axis=0)), list(mtrx.var(axis=1)), mtrx.var()],
    'standard deviation': [mtrx.std(axis=0), list(mtrx.std(axis=1)), mtrx.std()],
    'max': [list(mtrx.max(axis=0)), list(mtrx.max(axis=1)), mtrx.max()],
    'min': [list(mtrx.min(axis=0)), list(mtrx.min(axis=1)), mtrx.min()],
    'sum': [list(mtrx.sum(axis=0)), list(mtrx.sum(axis=1)), mtrx.sum()]
}

In [43]:
calc_dict

{'mean': [[np.float64(4.0), np.float64(5.0), np.float64(6.0)],
  [np.float64(2.0), np.float64(5.0), np.float64(8.0)],
  np.float64(5.0)],
 'variance': [[np.float64(6.0), np.float64(6.0), np.float64(6.0)],
  [np.float64(0.6666666666666666),
   np.float64(0.6666666666666666),
   np.float64(0.6666666666666666)],
  np.float64(6.666666666666667)],
 'standard deviation': [array([2.44948974, 2.44948974, 2.44948974]),
  [np.float64(0.816496580927726),
   np.float64(0.816496580927726),
   np.float64(0.816496580927726)],
  np.float64(2.581988897471611)],
 'max': [[np.int64(7), np.int64(8), np.int64(9)],
  [np.int64(3), np.int64(6), np.int64(9)],
  np.int64(9)],
 'min': [[np.int64(1), np.int64(2), np.int64(3)],
  [np.int64(1), np.int64(4), np.int64(7)],
  np.int64(1)],
 'sum': [[np.int64(12), np.int64(15), np.int64(18)],
  [np.int64(6), np.int64(15), np.int64(24)],
  np.int64(45)]}

If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers."

In [51]:
if len(matrix_list) < 9:
    raise ValueError("List must contain nine numbers.")

In the mean_var_std.py I will gather all parts together to solve the task!
